### ISSUE TITLE
ADM-CID not works

### ISSUE THREAD

**Issue by piars777** [eavanvalkenburg/pysiaalarm#16]
Hi,
My alarm uses adm-cid, i added it to HA without setting the encryption key because i can set max 8 char on my alarm, the configuration is ok but from HA the status is always unknown. 
Can you help me please?

**Comment by eavanvalkenburg** [comment]
Hey that is fantastic since I can't test that myself, please turn on logging for both the component and package (pysiaalarm) and report back to me here! Take note that you won't see a change in ha until you do something with the alarm itself

**Comment by piars777** [comment]
I set log level like this:
`logger:
  default: error
  logs:
    homeassistant.components.pysiaalarm: debug`

but i can't see any log in the console

**Comment by eavanvalkenburg** [comment]
you need:
```
logger:
  default: error
  logs:
    homeassistant.components.sia: debug 
    pysiaalarm: debug
```
